server:
  port: 8080 
  servlet:
    context-path: /
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    url: jdbc:mysql://localhost:3306/product?serverTimezone=Asia/Seoul
    username: product
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver  
      
    
    
